screen=[shadows] [water] [clouds] [other]
screen.shadows=SHADOW_RANGE SHADOW_RADIUS shadowMapResolution
screen.water=waveStrength
screen.clouds=cloudWaviness
screen.other=TRANSMODE portalWaveStrength


sliders=waveStrength cloudWaviness shadowMapResolution

